### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by gkwan-ibm** [paketo-buildpacks/liberty#202]
The [configuration](https://github.com/paketo-buildpacks/liberty#configuration) information is not clear enough
- `$BP_LIBERTY_VERSION`  
  -  need an example of how the version looks like, `22.0.0.7`
  - what value for the latest version?
- `$BP_LIBERTY_PROFILE`
  - beside `full`, what are the other values?
- `$BP_LIBERTY_CONTEXT_ROOT`
  - if the server.xml has an [application](https://openliberty.io/docs/latest/reference/config/application.html) named app defined, will also generate and override the context root?
- `$BP_LIBERTY_FEATURES` 
  - better point to a Open Liberty features doc, e.g. https://openliberty.io/docs/latest/reference/feature/feature-overview.html
- `$BP_LIBERTY_EXT_CONF_SHA256`
  - how the values look like? list the values or point to another doc

**Comment by dmikusa-pivotal** [comment]
> The [configuration](https://github.com/paketo-buildpacks/liberty#configuration) information is not clear enough

That's fair. Let me see if I can clarify things here & then I can take that and update the README.

> * `$BP_LIBERTY_VERSION`
>   
>   * need an example of how the version looks like, `22.0.0.7`
>   * what value for the latest version?

This is tricky because the versions change over time and if we list one then we get complaints if it's not kept up-to-date. Our automation for updating versions does not presently look at README.md or docs though, so it'll fall out-of-sync.

How about linking to the release notes? Every version of the buildpack we cut has a listing of the versions of OpenLiberty that can be installed in it's release notes.

> * `$BP_LIBERTY_PROFILE`
>   
>   * beside `full`, what are the other values?

I can add that:  kernel, microProfile4, microProfile5, webProfile8, webProfile9, javaee8, jakartaee9 and full.

This can change over time, but it's less likely and requires manual intervention so I'm OK listing these specifically.

> * `$BP_LIBERTY_CONTEXT_ROOT`
>   
>   * if the server.xml has an [application](https://openliberty.io/docs/latest/reference/config/application.html) named app defined, will also generate and override the context root?

I don't want to misspeak here, @hibell or @kevin-ortega could you take this one?

> * `$BP_LIBERTY_FEATURES`
>   
>   * better point to a Open Liberty features doc, e.g. https://openliberty.io/docs/latest/reference/feature/feature-overview.html

100%

> * `$BP_LIBERTY_EXT_CONF_SHA256`
>   
>   * how the values look like? list the values or point to another doc

It should just be a sha256 hash, so the first column of the output of `shasum -a 256`. ex: `ecf701f727d9e2d77c4aa49ac6fbbcc997278aca010bddeeb961c10cf54d435a`.

**Comment by hibell** [comment]
Sure.

> * $BP_LIBERTY_CONTEXT_ROOT
>
>   * if the server.xml has an [application](https://openliberty.io/docs/latest/reference/config/application.html) named app defined, will also generate and override the context root?

`BP_LIBERTY_CONTEXT_ROOT` will not override the context root if the server.xml already defines it for app. It is only to configure the value of context root used if the buildpack generates the application config.

**Comment by dmikusa-pivotal** [comment]
@gkwan-ibm - Please check out #205. If that looks good to you, I'll merge it. Feel free to make any additional suggestions for clarification on those settings. Happy to add more detail to that PR.

**Comment by kevin-ortega** [comment]
> 

`BP_LIBERTY_VERSION` does not have much value at the moment.  The buildpack only has one version of OL.  When we add an additional version you would specify it as `22.0.n`.

**Comment by dmikusa-pivotal** [comment]
@kevin-ortega Yes, that's a good point as well. It's kind of a limitation to the way that dependencies are managed right now. You can technically do it, but it gets messy for a number of use cases.

For what it's worth, this is an [early draft of a proposal](https://docs.google.com/document/d/1g5rRW-oE_v8Gdvz-CiCOK9z2rxg6L5XniKI25Zq2j6M/edit) that would allow us to support any number of versions.

**Comment by gkwan-ibm** [comment]
the inconsistent of `22.0.n` and `22.0.0.n` is no good for the users

**Comment by dmikusa-pivotal** [comment]
There's nothing we can change there at the moment. The buildpacks require semver and 22.0.0.n is not following semver. We have to squash down the version number in some way. We were initially using 22.0.0, but Kevin and I thought that 22.0.n made more sense as the last digit changes regularly.

I would try to not get too hung up on this though, because as Kevin mentioned there is only presently one version of Liberty included in the buildpack per release of the buildpack, whatever is the latest version. What this means is that there's not presently any reason to actually change the version number. You get what's bundled with the buildpack. As mentioned in my previous comment, that will change in the future and we'll be able to bundle multiple versions. That's also the point where we could attempt to match up version numbers and get away from the semver requirement.

**Comment by gkwan-ibm** [comment]
buildpack is already in production. Probably need to support both format `22.0.n` and `22.0.0.n`.
