### ISSUE TITLE
Unable to use custom server.xml when building the image

### ISSUE THREAD

**Issue by maciekgaszynski** [paketo-buildpacks/liberty#66]
## What happened?

* What were you attempting to do?
Tried to execute this buildpack against OpenLiberty starter created app 
https://openliberty.io/start/
hoping to have src/main/liberty/config/server.xml included in the image

* What did you expect to happen?
I wanted to use src/main/liberty/config/server.xml as a
/layers/paketo-buildpacks_open-liberty/open-liberty-runtime-full/usr/servers/defaultServer/server.xml in the image

* What was the actual behavior? Please provide log output, if possible.
Going through the code and docs I spotted that custom server.xml is possible with bindings. However, to me, it looks like it's only possible with bindings for the run image rather than the build image. 
The problem I see is that if I want to use e.g. 
```xml
    <featureManager>
        <feature>javaee-7.0</feature>
        <feature>microProfile-1.4</feature>
    </featureManager>
``` 
I need to bind server.xml when actually running the container rather than when building it. My understanding is that the recommended way of doing it (according to the OpenLiberty guide) is to include server.xml within the image.
Please let me know if there is some other way of adding standard features to server.xml in this buildpack.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version. pack
Pack:
  Version:  0.24.0
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.13.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8

* What buildpacks are you using? Please include versions.
paketo-buildpacks/java
gcr.io/paketo-buildpacks/open-liberty

paketo-buildpacks/ca-certificates   3.0.3
paketo-buildpacks/bellsoft-liberica 9.1.0
paketo-buildpacks/syft              1.7.0
paketo-buildpacks/apache-tomcat     7.1.0
paketo-buildpacks/dist-zip          5.1.0
paketo-buildpacks/spring-boot       5.5.0
paketo-buildpacks/open-liberty      0.3.2

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
paketobuildpacks/builder:base

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

any app generated with 
![image](https://user-images.githubusercontent.com/6057526/154695693-9d7eae57-f43b-4092-aeff-29d2782604e7.png)

`pack build -e BP_DEBUG --buildpack paketo-buildpacks/java --buildpack gcr.io/paketo-buildpacks/open-liberty app-name --path target/app-name`

## Checklist

* [ ] I have included log output. n/a
* [ ] The log output includes an error message. n/a
* [x] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
>Going through the code and docs I spotted that custom server.xml is possible with bindings. However, to me, it looks like it's only possible with bindings for the run image rather than the build image.

Yes, at the moment using the binding would be the route to make this work. We went with a binding here because a `server.xml` can have potentially sensitive information in it. Bindings essentially equate to Secrets when deploying on Kubernetes, so that is typically what we'll use for sensitive information.

If all you're trying to do is enable a particular feature, then a binding is probably overkill.

>I need to bind server.xml when actually running the container rather than when building it. My understanding is that the recommended way of doing it (according to the OpenLiberty guide) is to include server.xml within the image.
Please let me know if there is some other way of adding standard features to server.xml in this buildpack.

Bindings are the way that buildpacks handle sensitive information, as I mentioned above, they equate to Secrets when deploying on Kubernetes. This is why you need to specify it at run time. Because a binding is essentially secret information, we never put that into the image. That would leak sensitive information.

Again, your use case of just enabling features doesn't require any secrets so there's probably a smoother way we can handle that.

**Comment by dmikusa-pivotal** [comment]
FYI - @hibell for your thoughts.

**Comment by maciekgaszynski** [comment]
Thanks for the quick explanation. I just wanted to make sure I'm not missing any feature that's already in the buildpack. 
I agree that using secrets is overkill for this scenario, though it was the only way I could come up with in the current state of buildpack.

**Comment by dmikusa-pivotal** [comment]
Thanks for the feedback! This buildpack is still under pretty active development so it's good to hear additional use cases that we could support to improve the user experience.

**Comment by hibell** [comment]
@dmikusa-pivotal Is there a way to contribute the server.xml in the app’s source directory? Maven/Gradle delete this file before it unpacks the application archive to the app directory. The only way I could think about doing this is by adding a helper buildpack before build buildpack runs that copies the `src/main/liberty/config` to some layer.

**Comment by dmikusa-pivotal** [comment]
@hibell - It would be OK so long as the JAR/WAR produced contains the file. It seems like that is the case, the `pack build` command listed above is using `--path` and pointing to something (a JAR folder or JAR?) and it's not running Maven, so that must have everything in it.

If that's not the case, then yes. There would be some challenges with making that work. I think we could find a solution without needing to add a new buildpack. We recently added support for multiple build artifacts, so that might be an option.

**Comment by maciekgaszynski** [comment]
Here's the tree after invoking ./mvnw clean package. server.xml is not automatically processed and included by war plugin in the final war artifact. 

```app-name tree
.
├── Dockerfile
├── README.txt
├── mvnw
├── mvnw.cmd
├── pom.xml
├── src
│   └── main
│       ├── java
│       │   └── com
│       │       └── demo
│       │           └── rest
│       │               ├── RestApplication.java
│       │               └── SimpleEndpoint.java
│       └── liberty
│           └── config
│               └── server.xml
└── target
    ├── app-name
    │   ├── META-INF
    │   └── WEB-INF
    │       └── classes
    │           └── com
    │               └── demo
    │                   └── rest
    │                       ├── RestApplication.class
    │                       └── SimpleEndpoint.class
    ├── app-name.war
    ├── classes
    │   └── com
    │       └── demo
    │           └── rest
    │               ├── RestApplication.class
    │               └── SimpleEndpoint.class
```

The reason I used --path during pack invocation is that open-liberty buildpack is not able to pass detect phase successfully in this file tree (this is the structure generated by open liberty starter).

The way I see it as a beginner openliberty user is that if server.xml file is included in the application sources, it should be considered by the buildpack as the one to be used in the final image.

For your reference this is the Dockerfile generated by open liberty starter:
```Docker
FROM icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi

COPY --chown=1001:0 /src/main/liberty/config /config

RUN features.sh

COPY --chown=1001:0 target/*.war /config/apps

RUN configure.sh

```

**Comment by dmikusa-pivotal** [comment]
Thanks for the details @maciekgaszynski. Yes, I agree that it would be reasonable if we could make use of that file. Yes, that's going to be an issue though, because by the point the open-liberty buildpack runs, your application source has already been deleted. We delete source code at the end of the build phase because most people don't want it in their final image. I'm sure we can find some way around this, but for now, you'd have to include it in the image to make this work.

@hibell A couple of things come to mind...

1. There is an open RFC at the moment about having consistent include/exclude behavior for the deletion of source code. When that RFC is completed and implemented, you could potentially set it to exclude that file. The file should then exist in the original location when the open-liberty buildpack runs. You could then move it where it needs to go.
2. The build tools buildpacks (Maven, Gradle, etc..) now support the concept of building multiple artifacts. By default, it'll match against a single artifact which is a JAR/WAR/EAR. The file is then stored in a layer, and after we delete the source code its contents are extracted into `/workspace`. 

    If you change the pattern you can make it match multiple files/directories, so the pattern could be set to match the server.xml and the JAR/WAR/EAR. That's easy. The tricky part is what happens then. We still save the files to a layer and delete source code, but afterward instead of expanding the JAR/WAR/EAR to `/workspace`, we just copy all the files back into `/workspace`. You might be able to make this work, but the buildpack has to understand how to handle the JAR/WAR/EAR and not the exploded contents, which requires more logic.

    For what it's worth, I think we should support multiple files regardless, so this might be a good way to fix two issues at the same time. We're adding it into other buildpacks at the moment. It would allow for a user to build or deploy multiple JAR/WAR/EAR files, probably under different contexts. 

    The drawback of this approach is that the user would need to modify the pattern for the build tool to find multiple files. It's not something the buildpack could do, or you'd be back to adding another buildpack that runs before the build tools and I don't think we want to do that.
