### ISSUE TITLE
Determine packaged server name automatically

### ISSUE THREAD

**Issue by hibell** [paketo-buildpacks/liberty#83]
When using a packaged server with a non-default server name (i.e. `defaultServer`), it is required that `BP_OPEN_LIBERTY_SERVER_NAME` be set. If there is only one possible server to use and `BP_OPEN_LIBERTY_SERVER_NAME` is not set, we should automatically detect the server name.

Also, we may need to improve the error here also if a packaged server was provided but server was not found as it was not obvious when someone was not using the correct server name.

**Comment by dmikusa-pivotal** [comment]
I would like to add another edge case that we can improve here.

Right now if you set `BP_OPEN_LIBERTY_SERVER_NAME` things work as expected at build time. However, the linker helper also expects this variable to be set at runtime. If it's not the linker helper will use the default server name and it won't find server.xml for the custom-named server.

The issue here is that we use `BP_` to signify build-time env settings and `BPL_` to indicate launch-time settings, so passing `BP_OPEN_LIBERTY_SERVER_NAME` at launch time breaks that convention. We'd need the linker to look for `BPL_OPEN_LIBERTY_SERVER_NAME` to be consistent with that naming policy.

That said, I think we can probably make things even easier here. The buildpack knows the server name at build time, either cause the user sets it or we find a default as is indicated above. The buildpack can then set `BPI_OPEN_LIBERTY_SERVER_NAME` and pass that information to the linker at runtime. I would not consider the server name to be secret, so I think it's OK if we  embed that env variable into the image.

We'd just need the linker to look at `BPI_OPEN_LIBERTY_SERVER_NAME` and fail if it's not set, since the buildpack should always set that value if the default server name is used.
